name: setup nodejs

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

runs-on: ubuntu-latest

jobs: 
 build:
 
steps:
-uses: actions/checkout@v2
-name: setup node.js
uses: actions/setup-node@v2
with:
   node-version: '14'
   
-run: npm install
-run: npm test
